# Form implementation generated from reading ui file 'ui/WelcomeScreen.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(441, 307)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Welcome.sizePolicy().hasHeightForWidth())
        Welcome.setSizePolicy(sizePolicy)
        Welcome.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Welcome.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Welcome)
        self.gridLayout.setObjectName("gridLayout")
        self.registerButton = QtWidgets.QPushButton(parent=Welcome)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.registerButton, 2, 0, 1, 1)
        self.formWidget = QtWidgets.QWidget(parent=Welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formWidget.sizePolicy().hasHeightForWidth())
        self.formWidget.setSizePolicy(sizePolicy)
        self.formWidget.setObjectName("formWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loginButton = QtWidgets.QPushButton(parent=self.formWidget)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout_2.addWidget(self.loginButton, 4, 1, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_2.addWidget(self.usernameLineEdit, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(parent=self.formWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout_2.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.passwordLineEdit.setStyleSheet("")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_2.addWidget(self.passwordLineEdit, 1, 1, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(parent=self.formWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout_2.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(parent=self.formWidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(347, 130))
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_2.addWidget(self.statusLabel, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.formWidget, 0, 0, 1, 1)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Dialog"))
        self.registerButton.setText(_translate("Welcome", "Create new Business"))
        self.loginButton.setText(_translate("Welcome", "Login"))
        self.passwordLabel.setText(_translate("Welcome", "Password"))
        self.usernameLabel.setText(_translate("Welcome", "Username"))
